### ISSUE TITLE
Suporte para datas menores que o ano 2000

### ISSUE THREAD

**Issue by daldegam** [idxp/pa-datepicker#2]
A directive usa para ano por padrão o formato YY, porem não é possível informar uma data menor que o ano 2000.
Por exemplo: 03/03/1990

MM/dd/yy = 03/03/90 ele iria virar 2090;

**Comment by daldegam** [comment]
Talvez seja viável criar algo para setar o formato de uma forma global e não diretamente na directive.

**Comment by denislins** [comment]
Isso na verdade não é um bug. Caso seja necessário suportar os dois anos, basta usar um formato de data em que o ano tenha quatro dígitos.
