### ISSUE TITLE
Seleção do painel com o mês correto

### ISSUE THREAD

**Issue by daldegam** [idxp/pa-datepicker#3]
Quando você seta uma data por exemplo:

var a = new Date("2015-01-05T03:00:00");

Quando você abrir o calendário para selecionar uma data, ele irá abrir no mês corrente.
Ao invés de abrir no mês de Janeiro de 2015, ele iria abrir hoje em Março de 2015;

**Comment by denislins** [comment]
Fixed via 2e5ef3f70ca3b5db8d2c71b6a1720f57c0379440.
